
// Code generated by go-ioc. DO NOT EDIT.
package wire

import (
    "github.com/tuhuynh27/go-ioc/ioc"
    "github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/logger"
    "github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/message"
    "github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/notification"
)

func InitializeContainer() (*ioc.Container, error) {
    container := ioc.NewContainer()
    
    // Initialize StdoutLogger
    comp0 := &logger.StdoutLogger{
    }
    container.Register("github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/logger.StdoutLogger", comp0)
    
    // Initialize EmailService
    comp1 := &message.EmailService{
        Logger: comp0,
    }
    container.Register("github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/message.EmailService", comp1)
    
    // Initialize SMSService
    comp2 := &message.SMSService{
        Logger: comp0,
    }
    container.Register("github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/message.SMSService", comp2)
    
    // Initialize NotificationService
    comp3 := &notification.NotificationService{
        Logger: comp0,
        EmailSender: comp1,
        SmsSender: comp2,
    }
    container.Register("github.com/tuhuynh27/go-ioc/examples/ioc-example-simple/notification.NotificationService", comp3)
    
    return container, nil
}
